### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by polyclick** [ryanseddon/60fps-scroll#10]
Would be great if the timeout was configurable. 500ms is a bit too long for me.

**Comment by ryanseddon** [comment]
So, Chrome has been busy matching what other browsers do which is not trigger mouse events while the user is scrolling effectively deperacting the need for this little lib (yay!) it's already in canary and will make it's way to stable soon. https://www.chromestatus.com/feature/5697181675683840

I'll be updating this to let people know not to use this anymore once it reaches stable.
