### ISSUE TITLE
Deprecate project when chrome ships fix to stable

### ISSUE THREAD

**Issue by ryanseddon** [ryanseddon/60fps-scroll#11]
So this little lib was only useful for Chrome which was the only browser that didn't disable mouse events while the user was scrolling causing the paint storms and janky scrolling. 

They have since fixed this issue and have shipped it to canary, see [status](https://www.chromestatus.com/feature/5697181675683840).

Once it reaches stable I'll retire this project by updating the readme to make sure people don't use it. I'll keep it around the code for historical reasons.

I'll also update my blog posts, or even post a new one.

cc @paulirish

**Comment by dubstrike** [comment]
Thanks!

**Comment by xcy7e** [comment]
You may state this out on front page.....

**Comment by ryanseddon** [comment]
Done

**Comment by qodeboy** [comment]
@ryanseddon this package is cross-browser, right? So fixing this in chrome only should not mark it as deprecated, since it is still usefull in other browsers?

**Comment by paulirish** [comment]
@qodeboy no this fix was only targeting chrome. Safari, IE and FF didn't need it.

**Comment by ryanseddon** [comment]
@qodeboy what @paulirish said this is here for historical reasons now, no need to use anymore.
