### ISSUE TITLE
Continuing development

### ISSUE THREAD

**Issue by madagon** [ryanseddon/60fps-scroll#12]
hello guys,
i've had the same problem as mentioned in the article (follow-up-60fps-scroll). despite of using the latest version of google chrome, i still had the problem.
downloaded and included this library and it does the trick.
i believe the development shouldn't stop cuz it's still a problem even in the newest version of chrome.
the idea of using translate3d is great.

(tested on windows10)

**Comment by ryanseddon** [comment]
Hmm it should be fixed, seems like you should file an issue with chrome. You can of course still use this library but Chrome should handle this natively from now on.
