### ISSUE TITLE
Only works when scroll is in body

### ISSUE THREAD

**Issue by hilja** [ryanseddon/60fps-scroll#4]
I couldn't get this to work no matter what I did, am I missing something obvious...

Then again, the [jsbin demo][1] version of this works fine when scroll is in body. If scroll is in a container, it won't work. See what I mean here [here][2]. If I add the scroll to the container it starts behaving weirdly `container.addEventListener('scroll', function() {...`

[1]: http://jsbin.com/IdIhacE/2/quiet
[2]: http://jsbin.com/lonin/2/edit

**Comment by ryanseddon** [comment]
Project is deprecated.
